// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  name: __t.string(),
  attending: __t.bool(),
  plusOne: __t.bool().name("plus_one"),
  plusOneName: __t.option(__t.string()).name("plus_one_name"),
  dietaryNotes: __t.option(__t.string()).name("dietary_notes"),
  createdAt: __t.timestamp().name("created_at"),
});
