// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const BudgetItem = __t.object("BudgetItem", {
  id: __t.u64(),
  name: __t.string(),
  planned: __t.u64(),
  actual: __t.option(__t.u64()),
  paid: __t.bool(),
  createdAt: __t.timestamp(),
});
export type BudgetItem = __Infer<typeof BudgetItem>;

export const GameSession = __t.object("GameSession", {
  identity: __t.identity(),
  startedAt: __t.timestamp(),
});
export type GameSession = __Infer<typeof GameSession>;

export const Guest = __t.object("Guest", {
  id: __t.u64(),
  name: __t.string(),
  attending: __t.bool(),
  plusOne: __t.bool(),
  plusOneName: __t.option(__t.string()),
  dietaryNotes: __t.option(__t.string()),
  claimedBy: __t.option(__t.identity()),
  createdAt: __t.timestamp(),
});
export type Guest = __Infer<typeof Guest>;

export const HeartScore = __t.object("HeartScore", {
  id: __t.u64(),
  playerName: __t.string(),
  score: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type HeartScore = __Infer<typeof HeartScore>;

export const TimelineConfig = __t.object("TimelineConfig", {
  id: __t.u64(),
  released: __t.bool(),
});
export type TimelineConfig = __Infer<typeof TimelineConfig>;

export const TimelineEntry = __t.object("TimelineEntry", {
  id: __t.u64(),
  time: __t.string(),
  title: __t.string(),
  location: __t.option(__t.string()),
  sortOrder: __t.u64(),
});
export type TimelineEntry = __Infer<typeof TimelineEntry>;

export const UnclaimedGuests = __t.object("UnclaimedGuests", {});
export type UnclaimedGuests = __Infer<typeof UnclaimedGuests>;

export const WeddingTodo = __t.object("WeddingTodo", {
  id: __t.u64(),
  title: __t.string(),
  done: __t.bool(),
  sortOrder: __t.u64(),
  createdAt: __t.timestamp(),
});
export type WeddingTodo = __Infer<typeof WeddingTodo>;

