// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Guest = __t.object("Guest", {
  id: __t.u64(),
  name: __t.string(),
  attending: __t.bool(),
  plusOne: __t.bool(),
  plusOneName: __t.option(__t.string()),
  dietaryNotes: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type Guest = __Infer<typeof Guest>;

