// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Guest = __t.object("Guest", {
  id: __t.u64(),
  name: __t.string(),
  attending: __t.bool(),
  plusOne: __t.bool(),
  plusOneName: __t.option(__t.string()),
  dietaryNotes: __t.option(__t.string()),
  claimedBy: __t.option(__t.identity()),
  createdAt: __t.timestamp(),
});
export type Guest = __Infer<typeof Guest>;

export const HeartScore = __t.object("HeartScore", {
  id: __t.u64(),
  playerName: __t.string(),
  score: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type HeartScore = __Infer<typeof HeartScore>;

export const WeddingTodo = __t.object("WeddingTodo", {
  id: __t.u64(),
  title: __t.string(),
  done: __t.bool(),
  sortOrder: __t.u64(),
  createdAt: __t.timestamp(),
});
export type WeddingTodo = __Infer<typeof WeddingTodo>;

